- name: Fetch Instance Info
     os_server_info:
        cloud: openstack
        region_name: regionOne
     register: r_os_servers
	 
	 
- name: Delete instances
     openstack_server_state = 'absent' 
