# tasks file for osp-facts
   - name: Fetch Instance Info
     os_server_info:
      cloud: openstack
      region_name: regionOne
     register: result
   
   - name: Add host(s) to inventory
     add_host:
        name: "{{ result.public_v4 }}"
        group: 
          - "{{ result.metadata.group }}"
          - "{{ result.metadata.deployment_name }}"
     loop: "{{ result.openstack_servers }}"
     loop_control:
        loop_var: result
