---
 - name: Fetch Instance Info
   os_server_info:
        cloud: openstack
        region_name: regionOne
   register: r_instances
 - name: Add host(s) to inventory
   add_host:
      name: "{{ __instance.public_v4 }}"
      group: 
         - "{{ __instance.metadata.group }}"
         - "{{ __instance.metadata.deployment_name }}"
   loop: "{{ r_instances.openstack_servers }}"
   loop_control:
      loop_var: __instance
